import type { Metadata } from "next";
import { Inter, Orbitron, Rubik_Glitch  } from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({
  subsets: ['latin'],
  variable: '--font-orbitron',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const glitch = Rubik_Glitch({
  subsets: ['latin'],
  variable: '--font-glitch',
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${orbitron.variable} ${glitch.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
