import type { Metadata } from "next";
import { Inter, Shrikhand, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const shrikhand = Shrikhand({
  subsets: ['latin'],
  variable: '--font-shrikhand',
  weight: '400',
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${shrikhand.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
